### ISSUE TITLE
Typescript type errors for Array functions 

### ISSUE THREAD

**Issue by Carsair** [swz-gh/yare-typescript-template#3]
![image](https://user-images.githubusercontent.com/20178742/135027734-6fb13bd0-538e-4f78-8199-e4cc8e42e9e5.png)
![image](https://user-images.githubusercontent.com/20178742/135027742-5b7841ca-d9f4-44c6-9408-487bdf0d3ca9.png)

This seemed to fix it:
```
declare const spirits: {[id: string]: Spirit};
declare const my_spirits: Array<CircleSpirit | SquareSpirit | TriangleSpirit>;
```

**Comment by Carsair** [comment]
I think I should have made this issue here:

https://github.com/Jules-Bertholet/yareio-typescript-typings/

Please let me know if you want me to make an issue there

**Comment by swz-git** [comment]
I think this is an issue with typescript, what version do you have installed?

**Comment by Carsair** [comment]
Using 4.4.2 , This is a fresh install of yare-typescript-template and using main.ts

![image](https://user-images.githubusercontent.com/20178742/135539396-f7b84b82-16ea-4745-8b0a-4437ac12ca9d.png)
![image](https://user-images.githubusercontent.com/20178742/135539572-87986240-7f55-4d2e-af93-b0d7dbde4dd2.png)

**Comment by swz-git** [comment]
Since your typescript is updated, yes you should probably make an issue at https://github.com/Jules-Bertholet/yareio-typescript-typings/
